name: Mergify merge-queue labels copier
on:
  pull_request_target:
    types:
      - opened

jobs:
  mergify-merge-queue-labels-copier:
    runs-on: ubuntu-22.04
    steps:
      - name: Copying labels
        uses: Mergifyio/gha-mergify-merge-queue-labels-copier@main
        with:
          labels: docker
